import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { NavbarDemo } from "@/components/responsive-navbar";
import { ShootingStarsAndStarsBackgroundDemo } from "@/components/StarBackground";
import AnimatedFooter from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en"  webcrx="">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ShootingStarsAndStarsBackgroundDemo/>
        <NavbarDemo/>
        
        {children}
      </body>
    </html>
  );
}
